FileNames = ['dcache:/pnfs/cms/WAX/11/store/user/devdatta/NtuplesBprimeTobH/TTJets_HadronicMGDecays_8TeV-madgraph/BprimeTobH_987_1_ia4.root', 
'dcache:/pnfs/cms/WAX/11/store/user/devdatta/NtuplesBprimeTobH/TTJets_HadronicMGDecays_8TeV-madgraph/BprimeTobH_988_1_y27.root', 
'dcache:/pnfs/cms/WAX/11/store/user/devdatta/NtuplesBprimeTobH/TTJets_HadronicMGDecays_8TeV-madgraph/BprimeTobH_989_1_45p.root', 
'dcache:/pnfs/cms/WAX/11/store/user/devdatta/NtuplesBprimeTobH/TTJets_HadronicMGDecays_8TeV-madgraph/BprimeTobH_98_1_VIt.root', 
'dcache:/pnfs/cms/WAX/11/store/user/devdatta/NtuplesBprimeTobH/TTJets_HadronicMGDecays_8TeV-madgraph/BprimeTobH_990_1_eD6.root', 
'dcache:/pnfs/cms/WAX/11/store/user/devdatta/NtuplesBprimeTobH/TTJets_HadronicMGDecays_8TeV-madgraph/BprimeTobH_991_1_wZ9.root', 
'dcache:/pnfs/cms/WAX/11/store/user/devdatta/NtuplesBprimeTobH/TTJets_HadronicMGDecays_8TeV-madgraph/BprimeTobH_992_1_mIL.root', 
'dcache:/pnfs/cms/WAX/11/store/user/devdatta/NtuplesBprimeTobH/TTJets_HadronicMGDecays_8TeV-madgraph/BprimeTobH_993_1_dau.root', 
'dcache:/pnfs/cms/WAX/11/store/user/devdatta/NtuplesBprimeTobH/TTJets_HadronicMGDecays_8TeV-madgraph/BprimeTobH_994_1_fWq.root', 
'dcache:/pnfs/cms/WAX/11/store/user/devdatta/NtuplesBprimeTobH/TTJets_HadronicMGDecays_8TeV-madgraph/BprimeTobH_995_1_sXO.root', 
'dcache:/pnfs/cms/WAX/11/store/user/devdatta/NtuplesBprimeTobH/TTJets_HadronicMGDecays_8TeV-madgraph/BprimeTobH_996_1_ACa.root', 
'dcache:/pnfs/cms/WAX/11/store/user/devdatta/NtuplesBprimeTobH/TTJets_HadronicMGDecays_8TeV-madgraph/BprimeTobH_997_1_wRK.root', 
'dcache:/pnfs/cms/WAX/11/store/user/devdatta/NtuplesBprimeTobH/TTJets_HadronicMGDecays_8TeV-madgraph/BprimeTobH_998_1_I1H.root', 
'dcache:/pnfs/cms/WAX/11/store/user/devdatta/NtuplesBprimeTobH/TTJets_HadronicMGDecays_8TeV-madgraph/BprimeTobH_999_1_YLd.root', 
'dcache:/pnfs/cms/WAX/11/store/user/devdatta/NtuplesBprimeTobH/TTJets_HadronicMGDecays_8TeV-madgraph/BprimeTobH_99_1_9wA.root', 
'dcache:/pnfs/cms/WAX/11/store/user/devdatta/NtuplesBprimeTobH/TTJets_HadronicMGDecays_8TeV-madgraph/BprimeTobH_9_1_cJD.root', 
]
